apiVersion: v1
kind: Service 
metadata:
  name: gt-frontend-service
  labels:
    app: gt-frontend-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetport: 80
  selector:
    app: gt-frontend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gt-frontend-app
  template:
    metadata:
      labels:
        app: gt-frontend-app
    spec:
      containers:
      - name: gt-frontend-app
        image: ghcr.io/intersectmbo/govtool-frontend-prod:4253b82560bd2f14daa9c13c3c92ad951cc03ff7-25
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 5
        envFrom:
        - secretRef:
            name: fe-env-vars 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
