apiVersion: v1
kind: Service 
metadata:
  name: gt-outcomes-service
  namespace: govtool
  labels:
    app: gt-outcomes-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: gt-outcomes-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-outcomes-deployment
  namespace: govtool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gt-outcomes-app
  template:
    metadata:
      labels:
        app: gt-outcomes-app
    spec:
      containers:
      - name: gt-outcomes-app
        image: ghcr.io/aaboyle878/govtool-outcomes-pillar-backend:e08ed286979b0e7f5c846daed0ad3be7787af7a6-1
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"

        envFrom:
        - secretRef:
            name: oc-env-vars
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
