apiVersion: v1
kind: Service 
metadata:
  name: {{ include "gt-backend.fullname" .}}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: gt-backend-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 9876 }}
  selector:
    app: gt-backend-app