apiVersion: v1
kind: Service
metadata:
  name: {{ include "gt-pdf-db.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: pdf-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dbservice.port }}
      targetPort: {{ .Values.dbservice.targetPort }}
  selector:
    app: pdf-postgres