apiVersion: v1
kind: Service 
metadata:
  name: {{ include "gt-metadata.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: gt-metadata-validation-app
spec:
  type: ClusterIP
  ports:
  - name: https
    port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 3000 }}
  selector:
    app: gt-metadata-validation-app