apiVersion: v1
kind: Service 
metadata:
  name: {{ include "gt-outcomes.fullname" .}}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: gt-outcomes-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: gt-outcomes-app