apiVersion: v1
kind: Service
metadata:
  name: pdf-postgres
  namespace: govtool
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: pdf-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-postgres
  namespace: govtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-postgres
  template:
    metadata:
      labels:
        app: pdf-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: pdf-db-connect
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}  # ephemeral; use PVC for persistent storage
