apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "govtool-ingress.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.tls.hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Values.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
    {{- end }}
