apiVersion: v1
kind: Service 
metadata:
  name: gt-backend-service
  labels:
    app: gt-backend-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 9876
  selector:
    app: gt-backend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-backend-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: gt-backend-app
  template:
    metadata:
      labels:
        app: gt-backend-app
    spec:
      containers:
      - name: gt-backend-app
        image: ghcr.io/intersectmbo/govtool-backend-prod:4253b82560bd2f14daa9c13c3c92ad951cc03ff7-25
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
