apiVersion: v1
kind: Service 
metadata:
  name: gt-metadata-validation-service
  namespace: govtool
  labels:
    app: gt-metadata-validation-app
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 80
    targetPort: 3000
  selector:
    app: gt-metadata-validation-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-metadata-validation-deployment
  namespace: govtool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gt-metadata-validation-app
  template:
    metadata:
      labels:
        app: gt-metadata-validation-app
    spec:
      containers:
      - name: gt-metadata-validation-app
        image: ghcr.io/aaboyle878/govtool-metadata-validation-prod:3ac4e47c952d87e61757e25004719e2543255121-36
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"
        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
